# -*- coding: utf-8 -*-
"""Data_Lake.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJAs4TyEDgRjVmZS__OI5efA_oXnhSGm
"""

pip install requests

import requests
import time
import datetime

# --- WELLINGTON'S UPDATED CONFIGURATION ---
NYT_API_KEY = "XXXXXX"
# Ensure the PAR URL ends with /o/
URL_PAR_BRONZE = "XXXXXX"

def start_archive_ingestion(start_year, end_year):
    """
    Downloads full NYT archives (thousands of articles per month)
    and uploads them to OCI Bronze Layer.
    """
    current_date = datetime.datetime.now()

    for year in range(start_year, end_year + 1):
        for month in range(1, 13):
            # 1. Stop if we reach a future month in 2026
            if year == current_date.year and month > current_date.month:
                break

            print(f"📡 Requesting FULL ARCHIVE for {month:02d}/{year}...")

            # 2. Correct Endpoint for Archive API
            nyt_archive_url = f"https://api.nytimes.com/svc/archive/v1/{year}/{month}.json?api-key={NYT_API_KEY}"

            try:
                # Increased timeout to 90s because Archive files are LARGE (~20MB+)
                response_nyt = requests.get(nyt_archive_url, timeout=90)

                if response_nyt.status_code == 200:
                    # 3. Define the Hive-style path in OCI
                    object_path = f"01_bronze/nytimes/{year}/{month:02d}_archive.json"
                    oci_final_url = URL_PAR_BRONZE + object_path

                    # 4. Upload raw JSON to OCI
                    print(f"📤 Uploading {object_path} to OCI Object Storage...")
                    response_oci = requests.put(oci_final_url, json=response_nyt.json())

                    if response_oci.status_code == 200:
                        print(f"✅ SUCCESS: {object_path} is now in the Data Lake!")
                    else:
                        print(f"❌ OCI UPLOAD ERROR: {response_oci.status_code}")

                elif response_nyt.status_code == 401:
                    print("❌ AUTH ERROR: Check if 'Archive API' is enabled in NYT Portal.")
                    return # Stop script to fix API access

                elif response_nyt.status_code == 429:
                    print("⚠️ RATE LIMIT: NYT is busy. Waiting 60 seconds...")
                    time.sleep(60)
                else:
                    print(f"❌ NYT API ERROR: {response_nyt.status_code}")

            except Exception as e:
                print(f"💥 SYSTEM CRASH: {e}")

            # 5. Mandatory pause to respect NYT's API limits
            # Archive files are big; we don't want to spam the server.
            time.sleep(12)

# --- BOOTSTRAP ---
print("🚀 Starting Data Lake Population (2019-2026)...")
start_archive_ingestion(2019, 2026)



# SILVER SECTOR

pip install pandas pyarrow

import requests
import io
import pandas as pd
import datetime
import time

# --- CONFIGURATION ---
URL_PAR = "xxxxxxx"

def batch_transform_silver(start_year, end_year):
    """
    Automates the transformation of all Bronze JSON files into Silver Parquet files.
    """
    current_date = datetime.datetime.now()

    for year in range(start_year, end_year + 1):
        for month in range(1, 13):
            # Stop if we reach a future month in 2026
            if year == current_date.year and month > current_date.month:
                break

            bronze_path = f"01_bronze/nytimes/{year}/{month:02d}_archive.json"
            silver_path = f"02_silver/nytimes/{year}/{month:02d}_cleaned.parquet"

            print(f"🔄 Processing {month:02d}/{year}...")

            # 1. Download from Bronze
            response = requests.get(URL_PAR + bronze_path)

            if response.status_code == 200:
                try:
                    raw_json = response.json()
                    articles = raw_json.get('response', {}).get('docs', [])

                    if not articles:
                        print(f"⚠️ No articles found for {month:02d}/{year}. Skipping...")
                        continue

                    # 2. Transform with Pandas
                    df = pd.DataFrame(articles)

                    # 3. Clean and Structure
                    df_clean = pd.DataFrame({
                        "publish_date": pd.to_datetime(df['pub_date']).dt.date,
                        "headline": df['headline'].apply(lambda x: x.get('main') if isinstance(x, dict) else None),
                        "section": df['section_name'],
                        "abstract": df['abstract'],
                        "word_count": df['word_count'],
                        "web_url": df['web_url']
                    })

                    # 4. Save to Parquet Buffer (Memory)
                    parquet_buffer = io.BytesIO()
                    df_clean.to_parquet(parquet_buffer, engine='pyarrow', index=False)
                    parquet_buffer.seek(0)

                    # 5. Upload to Silver Layer
                    print(f"📤 Uploading Parquet to Silver: {silver_path}")
                    res_silver = requests.put(URL_PAR + silver_path, data=parquet_buffer)

                    if res_silver.status_code == 200:
                        print(f"✅ Success: {month:02d}/{year} is Silver!")
                    else:
                        print(f"❌ Upload Error {res_silver.status_code}")

                except Exception as e:
                    print(f"💥 Error processing {month:02d}/{year}: {e}")
            else:
                print(f"❌ Bronze file not found: {bronze_path} (Status {response.status_code})")

            # Short sleep to avoid overwhelming your local network/RAM
            time.sleep(1)

# --- START BATCH PROCESS ---
print("🚀 Starting Massive Silver Transformation (2019-2026)...")
batch_transform_silver(2019, 2026)

#GOLD

import pandas as pd
import requests
import io

# --- CONFIGURATION ---
URL_PAR = "xxxxxxxxxxx"

def generate_gold_analytics(start_year, end_year):
    all_data = []

    print("🏆 Collecting data from Silver to create GOLD insights...")

    for year in range(start_year, end_year + 1):
        for month in range(1, 13):
            silver_path = f"02_silver/nytimes/{year}/{month:02d}_cleaned.parquet"

            # Download from Silver
            response = requests.get(URL_PAR + silver_path)

            if response.status_code == 200:
                # Read Parquet from memory
                df_month = pd.read_parquet(io.BytesIO(response.content))
                all_data.append(df_month)
            else:
                continue # Skip if month doesn't exist yet

    # 1. Combine all years and months into ONE big table
    full_df = pd.concat(all_data, ignore_index=True)

    # 2. Perform Gold Analysis: Group by Section and Year
    # Example: How many articles per section each year?
    full_df['year'] = pd.to_datetime(full_df['publish_date']).dt.year
    gold_analysis = full_df.groupby(['year', 'section']).size().reset_index(name='article_count')

    # 3. Save the Gold Insight back to OCI
    gold_path = "03_gold/analytics/articles_distribution_2019_2026.csv"
    csv_buffer = io.StringIO()
    gold_analysis.to_csv(csv_buffer, index=False)

    print(f"📤 Uploading Gold Insight to {gold_path}...")
    requests.put(URL_PAR + gold_path, data=csv_buffer.getvalue())

    print("✅ GOLD LAYER UPDATED! Ready for Dashboard.")

# --- RUN GOLD PROCESS ---
generate_gold_analytics(2019, 2024)



# ACESSING DATA

import pandas as pd
import requests
import io

# Your PAR URL for the Silver folder
URL_PAR = "xxxxxxxxxx"

def consult_news(category="U.S."):
    # 1. Download the Parquet file into memory
    response = requests.get(URL_PAR)

    if response.status_code == 200:
        # 2. Load into Pandas
        df = pd.read_parquet(io.BytesIO(response.content))

        # 3. Filter by 'section' (Category)
        # In NYT, "Internal" news is usually under the "U.S." or "National" section
        filtered_news = df[df['section'] == category]

        print(f"--- Top 10 News in {category} ---")
        print(filtered_news[['publish_date', 'headline']].head(10))
    else:
        print("Error accessing the Data Lake")

consult_news("U.S.") # Consult Internal/U.S. news